repos:
  # python
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.278
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
